### ISSUE TITLE
Potential Endless Recursion

### ISSUE THREAD

**Issue by ecolinkbgruber** [STMicroelectronics/sths34pf80-pid#2]
I have an issue where I see _sths34pf80_odr_safe_set()_ call _sths34pf80_algo_reset()_ which calls _sths34pf80_func_cfg_write()_ which calls _sths34pf80_odr_safe_set()_ etc... 

```
int32_t sths34pf80_algo_reset(stmdev_ctx_t *ctx)
{
  ...
  ret = sths34pf80_func_cfg_write(ctx, STHS34PF80_RESET_ALGO, &tmp, 1);//I suggest probably replacing this line.
 ...
}
```

**Comment by avisconti** [comment]
@ecolinkbgruber Can you possibly test PR #4?
