### ISSUE TITLE
Can't seem to get examples working on RPi Pico

### ISSUE THREAD

**Issue by Rocketmagnet** [STMicroelectronics/sths34pf80-pid#3]
I am trying out your example code: **sths34pf80_tmos_data_polling.c** and **sths34pf80_tmos_presence_detection.c** on the Raspberry Pi Pico (RP2040) in C using VS Code, but neither of them seem to work.

I have created appropriate platform_write() and platform_read() functions, and verified that they work using a logic analyser.

sths34pf80_device_id_get(&dev_ctx, &whoami) gives the correct value of 0xD3 as expected.

However, in sths34pf80_tmos_data_polling, the code seems to get stuck in sths34pf80_safe_power_down(), waiting for DRDY to go high. I added some printf() statements to the code to log where which functions from sths34pf80_tmos_data_polling.c are being called, and what reads/writes happen. Here is that log:

`sths34pf80_device_id_get(&dev_ctx, &whoami);`
`  read  0xd3 <- [0x0f]  (1 bytes)				# 0xD3 read back correctly`
`  `
`sths34pf80_avg_tobject_num_set(&dev_ctx, STHS34PF80_AVG_TMOS_32);`
`  read  0x02 <- [0x10]  (1 bytes)`
`  write 0x02 -> [0x10]`
`  `
`sths34pf80_avg_tambient_num_set(&dev_ctx, STHS34PF80_AVG_T_8);`
`  read  0x02 <- [0x10]  (1 bytes)`
`  write 0x02 -> [0x10]`
` `
`sths34pf80_lpf_m_bandwidth_get(&dev_ctx, &lpf_m);`
`  read  0x04 <- [0x0c]  (1 bytes)`
`  `
`sths34pf80_lpf_p_bandwidth_get(&dev_ctx, &lpf_p);`
`  read  0x22 <- [0x0d]  (1 bytes)`
`  `
`sths34pf80_lpf_p_m_bandwidth_get(&dev_ctx, &lpf_p_m);`
`  read  0x04 <- [0x0c]  (1 bytes)`
`  `
`sths34pf80_lpf_a_t_bandwidth_get(&dev_ctx, &lpf_a_t);`
`  read  0x22 <- [0x0d]  (1 bytes)`
`  `
`lpf_m: 04, lpf_p: 04, lpf_p_m: 00, lpf_a_t: 02`
`  `
`sths34pf80_block_data_update_set(&dev_ctx, 1);`
`  read 0x18 <- [0x20]  (1 bytes)`
`  write 0x18 -> [0x20]`
`  `
`sths34pf80_odr_set(&dev_ctx, STHS34PF80_ODR_AT_30Hz);`
`  sths34pf80_read_reg(ctx, STHS34PF80_CTRL1, (uint8_t *)&ctrl1, 1);`
`    read 0x18 <- [0x20]  (1 bytes)`
` `
`  sths34pf80_read_reg(ctx, STHS34PF80_AVG_TRIM, (uint8_t *)&avg_trim, 1);`
`    read 0x02 <- [0x10]  (1 bytes)`
`	`
`  sths34pf80_odr_safe_set(ctx, ctrl1, (uint8_t)val);`
`    sths34pf80_safe_power_down(ctx, ctrl1);`
`	`
`	  sths34pf80_read_reg(ctx, STHS34PF80_FUNC_STATUS, (uint8_t *)&func_status, 1);`
`		read 0x00 <- [0x25]  (1 bytes)`
`		`
`	  sths34pf80_drdy_status_get(ctx, &status);`
`        read 0x03 <- [0x23]  (1 bytes)`

At this point, it get stuck in a loop, reading register 0x23 (STATUS) continuously, waiting for bit 2 (DRDY) to go high. It never does.

**Comment by avisconti** [comment]
Seems same issue as #2.
I'll work on it asap

**Comment by Rocketmagnet** [comment]
Hmm. Strangely I seem to have got it working now, but I can't say exactly what I changed to make it work. I was adding printf() statements to track execution, and I changed the status variable in sths34pf80_drdy_status_get() to volatile. Then it worked. So I put it back to non-volatile to confirm that that was the change that made it work. But it still worked. Damn, shoulda committed the code before I started messing around.

**Comment by Rocketmagnet** [comment]
I half wonder if this problem was an illusion created by the fact that sths34pf80_drdy_status_get() gets called quite a lot of times before DRDY goes high, and if there are any printf() statements in the loop, it can look crazy on the console.

**Comment by avisconti** [comment]
> I half wonder if this problem was an illusion created by the fact that sths34pf80_drdy_status_get() gets called quite a lot of times before DRDY goes high, and if there are any printf() statements in the loop, it can look crazy on the console.

No no, the issue is real. Someone else reported it on #2. But I forgot to address it in the first place.

**Comment by avisconti** [comment]
@Rocketmagnet can you test PR #4? Is a temptative solution, but not well tested on our side.
